name: Build

on:
  push:
    branches: ["main"]
    tags: ["v*", "*.*.*"]
  workflow_dispatch:

jobs:
  build:
    name: Build Artifacts
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Validate Gradle Wrapper
#        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          # Cache handled by gradle/actions/setup-gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable (Unix)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build (skip tests) – Unix
        if: runner.os != 'Windows'
        run: ./gradlew build -x test --no-daemon --stacktrace

      - name: Build (skip tests) – Windows
        if: runner.os == 'Windows'
        run: ./gradlew.bat build -x test --no-daemon --stacktrace

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ runner.os }}
          path: build/libs/*.jar
